version: "3.1"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafkaBroker1:
    image: 'bitnami/kafka:latest'
    ports:
      - '9077:9077'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9077
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafkaBroker1:9077
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  kafkaBroker2:
    image: 'bitnami/kafka:latest'
    ports:
      - '9078:9078'
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9078
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafkaBroker2:9078
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  
  kafkaBroker3:
    image: 'bitnami/kafka:latest'
    ports:
      - '9079:9079'
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9079
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafkaBroker3:9079
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  api: 
    build: 
        context: ./api-kafka-admin-with-python
        dockerfile: Dockerfile
    restart: always
    depends_on: 
        - kafkaBroker3
    ports: 
        - "80:80"